package View;

import Controller.StudentController;
import Controller.TeacherController;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kusal
 */
public class Addstu extends javax.swing.JFrame {

  
    public Addstu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        addressf = new javax.swing.JTextField();
        Form = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        smbtn = new javax.swing.JRadioButton();
        sfbtn = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Studentview = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        backHome = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Student Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Date of Birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        name.setToolTipText("Enter your name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 247, -1));

        dob.setToolTipText("Enter your Date of Birth");
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 247, -1));

        phn.setToolTipText("Enter Phone");
        phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnActionPerformed(evt);
            }
        });
        jPanel1.add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 149, -1));

        addressf.setToolTipText("Enter Address");
        jPanel1.add(addressf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 247, -1));

        Form.setBackground(new java.awt.Color(255, 255, 255));
        Form.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Form.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Form.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        buttonGroup1.add(smbtn);
        smbtn.setText("Male");
        Form.add(smbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        buttonGroup1.add(sfbtn);
        sfbtn.setText("Female");
        Form.add(sfbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kusal\\Pictures\\New folder\\icons8-clear-24.png")); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Form.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kusal\\Pictures\\New folder\\icons8-submit-24.png")); // NOI18N
        jButton1.setText("Submit");
        jButton1.setToolTipText("If you press the submit button, The details will be add to the data base");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Form.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jPanel1.add(Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 640, 630));

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kusal\\Pictures\\New folder\\icons8-view-24.png")); // NOI18N
        jMenu1.setText("View");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Studentview.setText("StudentDatabase");
        Studentview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentviewActionPerformed(evt);
            }
        });
        jMenu1.add(Studentview);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Back");

        backHome.setText("Home");
        backHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeActionPerformed(evt);
            }
        });
        jMenu2.add(backHome);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1386, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Gender = null;
if (smbtn.isSelected()) {
Gender = "Male";
} else if (sfbtn.isSelected()) {
Gender = "Female";
}

StudentController.Form(name.getText(),dob.getText(),Gender,phn.getText(), addressf.getText() );

clearField();

        
    
   /* String StudentName = name.getText();
    String DateOfBirth = dob.getText();
    
    String gender = null;
 if (smbtn.isSelected()) {
 gender = "Male";
 } else if (sfbtn.isSelected()) {
 gender = "Female";
 }
    
    String Phone = phn.getText();
    String Address = addressf.getText();

    try {
        Connection con = DBconnector.getCone();
        Statement st = con.createStatement();

        st.executeUpdate("INSERT INTO students (StudentName,DateOfBirth,Gender,Phone,Address) VALUES('" + StudentName + "','" + DateOfBirth + "','" + gender + "','" + Phone + "','" + Address + "')");

        JOptionPane.showMessageDialog(null, "Data Successfully Inserted");
        
        //clear fields data
        name.setText("");
        dob.setText("");
        sfbtn.setSelected(false);
        smbtn.setSelected(true);
        phn.setText("");
        addressf.setText("");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " );
       
    }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        name.setText("");
        dob.setText("");
        
        smbtn.setSelected(true);
        phn.setText("");
        addressf.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void StudentviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentviewActionPerformed
        // TODO add your handling code here:
        
        setVisible (false);
        StudentDetails object = new StudentDetails();
        object.setVisible(true);
    }//GEN-LAST:event_StudentviewActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        Home object = new Home();
        object.setVisible(true);
    }//GEN-LAST:event_backHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> {
            new Addstu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form;
    private javax.swing.JMenuItem Studentview;
    private javax.swing.JTextField addressf;
    private javax.swing.JMenuItem backHome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phn;
    private javax.swing.JRadioButton sfbtn;
    private javax.swing.JRadioButton smbtn;
    // End of variables declaration//GEN-END:variables

    private void clearField() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
